# Generated by Django 5.1.3 on 2025-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_category_image_category_is_active_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
