# Generated by Django 5.1.3 on 2025-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_paid_at_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="tracking_id",
        ),
        migrations.AddField(
            model_name="shipment",
            name="awb_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shiprocket_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
