# Generated by Django 5.1.3 on 2025-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="banner",
            name="theme",
            field=models.CharField(
                choices=[
                    ("tech", "Tech / Electronics"),
                    ("fashion", "Fashion / Lifestyle"),
                    ("grocery", "Grocery / Daily Needs"),
                    ("dark", "Flash Sale / Dark"),
                ],
                default="tech",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
