# Generated by Django 5.1.3 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_banner_subtitle_banner_theme_alter_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="layout",
            field=models.CharField(
                choices=[
                    ("text_left", "Text Left"),
                    ("text_right", "Text Right"),
                    ("full_image", "Full Image"),
                ],
                default="text_left",
                max_length=20,
            ),
        ),
    ]
