# Generated by Django 5.1.3 on 2025-12-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_banner_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="theme",
            field=models.CharField(
                choices=[
                    ("tech", "Tech / Electronics"),
                    ("fashion", "Fashion / Lifestyle"),
                    ("grocery", "Grocery / Daily Needs"),
                    ("dark", "Flash Sale / Dark"),
                    ("republic", "Republic Day 🇮🇳"),
                ],
                default="tech",
                max_length=20,
            ),
        ),
    ]
