# Generated by Django 5.1.3 on 2025-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_banner_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="mrp_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="offer_price",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10),
            preserve_default=False,
        ),
    ]
