# Generated by Django 5.1.3 on 2025-12-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_recentlyviewedproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("products", "Selected Products"),
                            ("category", "Category Products"),
                            ("discount", "Discount Based"),
                            ("latest", "Latest Products"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_discount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used only for discount based section",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="core.product")),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
