# Generated by Django 5.1.3 on 2026-01-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_orderitem_variant_alter_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
