# Generated by Django 5.2.4 on 2025-09-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_delete_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shipment",
        ),
    ]
